name:                assignment1
version:             0.1.0.0
github:              "slow-J/assignment1"
license:             BSD3
author:              "Jakub Slowinski"
maintainer:          "example@example.com"
copyright:           "2019 Jakub Slowinski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/slow-J/assignment1#readme>

dependencies:
- base >= 4.7 && < 5
- parallel
- old-time
- random
- deepseq

library:
  source-dirs: src

executables:
  assignment1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    # - -O2
    - -eventlog
    - -with-rtsopts=-N
    dependencies:
    - assignment1

tests:
  assignment1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -eventlog
    - -with-rtsopts=-N
    dependencies:
    - assignment1
